[package]
name = "taml"
version = "0.0.0-dev"
authors = ["Tamme Schichler <tamme@schichler.dev>"]
edition = "2018"
publish = false

[lib]

[[bin]]
name = "taml"
doc = false
required-features = ["bin-dependencies"]

[dependencies]
argh = { version = "0.1.3", optional = true }
gnaw = { path = "../gnaw" }
lazy-transform-str = { path = "../lazy-transform-str" }
logos = "0.11.4"
serde = "1.0.114"
smartstring = "0.2.3"
woc = { path = "../woc" }

[features]
bin-dependencies = ["argh"]
default = ["bin-dependencies"]
